import type { Metadata } from "next";
import "./globals.css";
import { JetBrains_Mono } from 'next/font/google';
import localFont from 'next/font/local'

const jetbrains = JetBrains_Mono({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
  variable: '--font-jetbrains',
});

const pretendard = localFont({
  src: '../fonts/PretendardVariable.woff2',
  display: 'swap',
  variable: '--font-pretendard',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${jetbrains.variable} ${pretendard.variable}`}>
      <body>
        {children}
      </body>
    </html>
  );
}
